version: 2.1
orbs:
  git-release-information: cropster/git-release-information@latest:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - git-release-information/install_mergestat
      - git-release-information/send_release_commit_list:
          repo_name: Infrastructure     
          slack_channel: $SLACK_WEBHOOK_URL	

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: cropster/git-release-information
          vcs_type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
